// Port of `Gmx::GmxPlugin` from src/plugins/gmx/gmxplugin.cpp.
//
// Produces the `.room.gmx` XML structure GameMaker Studio 1.x consumes.
// This minimal port emits the room header, an empty `<views>` block and
// per-cell `<tile>` entries for each tile layer. Object groups, instance
// emission, scaling, view sorting and physics props are intentionally
// skipped — see TODOs.

import {
  type Map as TiledMap,
  MapOrientation,
  type Tileset,
  type Tile,
} from '@tiled-ts/core';

import { FormatCapability, type FileFormat } from './formatRegistry.js';

export function writeGmx(map: TiledMap): string {
  const lines: string[] = [];
  lines.push('<!-- This Document is generated by Tiled, if you edit it by hand then you do so at your own risk! -->');
  lines.push('<room>');

  const pixelW = map.tileWidth * map.width;
  const pixelH = map.tileHeight * map.height;

  push(lines, 1, `<width>${pixelW}</width>`);
  push(lines, 1, `<height>${pixelH}</height>`);
  push(lines, 1, `<vsnap>${map.tileHeight}</vsnap>`);
  push(lines, 1, `<hsnap>${map.tileWidth}</hsnap>`);
  push(lines, 1, `<isometric>${gmBool(map.orientation === MapOrientation.Isometric)}</isometric>`);
  push(lines, 1, `<speed>30</speed>`);
  push(lines, 1, `<persistent>0</persistent>`);
  push(lines, 1, `<clearViewBackground>0</clearViewBackground>`);
  push(lines, 1, `<clearDisplayBuffer>-1</clearDisplayBuffer>`);
  push(lines, 1, `<code></code>`);
  push(lines, 1, `<enableViews>0</enableViews>`);

  // TODO: emit views, instances and physics-world properties.
  push(lines, 1, '<instances/>');

  // Tiles
  push(lines, 1, '<tiles>');
  let tileId = 0;
  let depth = 1_000_000;
  for (const layer of map.tileLayers()) {
    depth -= 1;
    for (let y = 0; y < layer.height; y++) {
      for (let x = 0; x < layer.width; x++) {
        const cell = layer.cellAt(x, y);
        const tile = cell.tile();
        if (!cell.tileset || !tile) continue;
        tileId += 1;
        push(lines, 2, formatTile(map, cell.tileset, tile, x, y, cell.flippedHorizontally(), cell.flippedVertically(), tileId, depth));
      }
    }
  }
  push(lines, 1, '</tiles>');

  push(lines, 1, '<PhysicsWorld>0</PhysicsWorld>');
  push(lines, 1, `<PhysicsWorldTop>0</PhysicsWorldTop>`);
  push(lines, 1, `<PhysicsWorldLeft>0</PhysicsWorldLeft>`);
  push(lines, 1, `<PhysicsWorldRight>${pixelW}</PhysicsWorldRight>`);
  push(lines, 1, `<PhysicsWorldBottom>${pixelH}</PhysicsWorldBottom>`);
  push(lines, 1, `<PhysicsWorldGravityX>0</PhysicsWorldGravityX>`);
  push(lines, 1, `<PhysicsWorldGravityY>10</PhysicsWorldGravityY>`);
  push(lines, 1, `<PhysicsWorldPixToMeters>0.1</PhysicsWorldPixToMeters>`);

  lines.push('</room>');
  return lines.join('\n') + '\n';
}

function formatTile(
  map: TiledMap,
  tileset: Tileset,
  tile: Tile,
  x: number,
  y: number,
  flippedH: boolean,
  flippedV: boolean,
  id: number,
  depth: number,
): string {
  let scaleX = 1;
  let scaleY = 1;
  let pixelX = x * map.tileWidth;
  let pixelY = y * map.tileHeight;
  if (flippedH) {
    scaleX = -1;
    pixelX += tileset.tileWidth;
  }
  if (flippedV) {
    scaleY = -1;
    pixelY += tileset.tileHeight;
  }

  const columns = tileset.columnCount || 1;
  const xInGrid = tile.id % columns;
  const yInGrid = Math.floor(tile.id / columns);
  const xo = tileset.margin + (tileset.tileSpacing + tileset.tileWidth) * xInGrid;
  const yo = tileset.margin + (tileset.tileSpacing + tileset.tileHeight) * yInGrid;

  const attrs = [
    `bgName="${escapeAttr(tileset.name)}"`,
    `x="${pixelX}"`,
    `y="${pixelY}"`,
    `w="${tileset.tileWidth}"`,
    `h="${tileset.tileHeight}"`,
    `xo="${xo}"`,
    `yo="${yo}"`,
    `id="${id}"`,
    `depth="${depth}"`,
    `locked="0"`,
    `colour="4294967295"`,
    `scaleX="${scaleX}"`,
    `scaleY="${scaleY}"`,
  ];
  return `<tile ${attrs.join(' ')}/>`;
}

function gmBool(b: boolean): string {
  // GameMaker uses -1 for true and 0 for false in numeric attributes.
  return b ? '-1' : '0';
}

function escapeAttr(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function push(out: string[], indent: number, line: string): void {
  out.push('  '.repeat(indent) + line);
}

/* ─────────────────────────── plugin descriptor ────────────────────────────── */

export const gmxPlugin: FileFormat = {
  id: 'gmx',
  name: 'GameMaker Studio 1.x room',
  extension: 'gmx',
  capabilities: FormatCapability.Write,
  write(map) {
    return { 'map.room.gmx': writeGmx(map) };
  },
};
