// Port of `enum UndoCommands` from src/tiled/undocommands.h.
//
// Stable numeric ids used to decide whether two adjacent commands should merge
// (`mergeWith`). Keep values 1:1 with upstream so cross-language plugins can
// reason about command kinds identically.

export enum UndoCommandId {
  ChangeClassName = 0,
  ChangeImageLayerImageSource,
  ChangeImageLayerRepeatX,
  ChangeImageLayerRepeatY,
  ChangeImageLayerTransparentColor,
  ChangeLayerBlendMode,
  ChangeLayerLocked,
  ChangeLayerName,
  ChangeLayerOffset,
  ChangeLayerOpacity,
  ChangeLayerParallaxFactor,
  ChangeLayerTintColor,
  ChangeLayerVisible,
  ChangeMapBackgroundColor,
  ChangeMapChunkSize,
  ChangeMapCompressionLevel,
  ChangeMapHexSideLength,
  ChangeMapInfinite,
  ChangeMapLayerDataFormat,
  ChangeMapObject,
  ChangeMapObjectTransform,
  ChangeMapOrientation,
  ChangeMapParallaxOrigin,
  ChangeMapRenderOrder,
  ChangeMapSkew,
  ChangeMapStaggerAxis,
  ChangeMapStaggerIndex,
  ChangeMapTileSize,
  ChangeObjectGroupColor,
  ChangeObjectGroupDrawOrder,
  ChangeSelectedArea,
  ChangeTileImageRect,
  ChangeTileProbability,
  ChangeTileWangId,
  ChangeTilesetName,
  ChangeTilesetTileOffset,
  ChangeWangColorName,
  ChangeWangSetName,
  EraseTiles,
  PaintTileLayer,
  SetMapRect,
  SetProperty,
}
